config/routes.rb
Rails.application.routes.draw do

  root :to => "articles#index"

  resources :articles do
    resources :comments
  end

  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :message => "can't be blank"
  validates_presence_of :body, :message => "can't be blank"

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments

  def published?
    published_at.present?
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles

  default_scope lambda {order ("categories.name")}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates_presence_of :name, :email, :body
  validate :article_should_be_published

  def article_should_be_published
    errors.add(:article_id, "is not published yet") if article && !article.published?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  validates_uniqueness_of :email
  validates_length_of :email, :within => 5..50
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/

  validates_confirmation_of :password
  validates_length_of :password, :within => 4..20
  #validates_presence_of :password, :if => :password_required?

  has_many :articles, -> {order("published_at DESC, title ASC")}, :dependent => :nullify
  has_many :replies, :through => :articles, :source => :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => "Your article was succesfully created!")}
        format.json { render action: 'show', status: :created, location: @article}
      else
        format.html { render action: 'new'}
        format.json { render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated!"}
        format.json { head :no_content}
      else
        format.html { render action: 'edit'}
        format.json { render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed. :(' }
      format.json {head :no_content}
    end
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :location, :body, :published_at, :category_ids => [])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_article, :except => :destroy

  def create
    @comment = @article.comments.new(comment_params)
    if @comment.save
      redirect_to @article, notice: "Thanks for your comment!"
    else
      redirect_to @article, notice: "Sorry, there's something wrong with your comment"
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article, notice: "Comment Deleted :("
  end

  private
  def load_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :email, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to articles_path, notice: "Wow, You are a user now!"
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to articles_path, notice: "User info was updated"
    else
      render action: 'edit'
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
    <h3>
      <%= link_to article.title, article %>
        <span class="actions">
          <%= link_to "Modify", edit_article_path(article) %>
        </span>
    </h3>
    <%= simple_format article.body %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <div id="error_container">
          <h2><%= pluralize(@article.errors.count, "error") %> didn't let you save this article:</h2>

          <ul>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :location %><br />
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label "Categories" %><br />
      <% Category.all.each do |category| %>
        <%= check_box_tag 'article[category_ids][]', category.id, @article.category_ids.include?(category.id), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name, class:"check_box" %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label "Tell us what you think ;)" %><br />
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.label :published_at %><br />
      <%= f.date_select :published_at %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div class="back">
  <%= link_to "Back to the list of articles", articles_path %>
</div>

<h1>Modify article</h1>
<p>You can change something in your article or delete it</p>

<%= render 'form' %>

<%= link_to "Show", article_path %><br />
<%= link_to "Delete", @article, confirm: "Are you sure?", :method => :delete %><br />

app/views/articles/index.html.erb
<h1>Something to read:</h1>

<div id="articles">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="back">
  <%= link_to "Back to the list of articles", articles_path %>
</div>

<h1>New article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="back">
  <%= link_to "Back to the list of articles", articles_path %>
</div>

<%= render @article %>

<h3>Comments:</h3>
<div id="comments">
  <%= render @article.comments %>
</div>

<%= render :file => "comments/new" %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <h3>
      <%= comment.name %>, "<%= comment.email %>", said:
        <span class="actions">
          <%= link_to "Delete", [@article, comment], confirm: "Are you sure?", :method => :delete %>
        </span>
    </h3>
    <%= comment.body %>
<% end %>

app/views/comments/new.html.erb
<%= form_for([@article, @article.comments.new]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.submit 'Add' %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <h1><%= link_to "Rails-blog", root_path %></h1>
  <div id = "user_bar">
    <%= link_to "New Article", new_article_path %>
    <%= link_to "New User", new_user_path %>
  </div>
</div>

<div id="main">
  <%= content_tag(:p, notice, :class => "notice") if notice.present? %>
  <%= content_tag(:p, alert, :class => "alert")if alert.present? %>
  <%= yield %>
</div>

<div id="footer">
  A simple blog built in the night with love to Rails...
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div id="error_container">
          <h2><%= pluralize(@user.errors.count, "error") %> didn't let this user to be saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label "Enter your e-mail, please" %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.text_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/users/edit.html.erb
<h1>Not much to EDIT, but you can do it!</h1>

<%= render 'form' %>

<%= link_to "Back to Articles", articles_path %>

app/views/users/new.html.erb
<div class="back">
  <%= link_to "Back to the list of articles", articles_path %>
</div>

<h1>Be our New User</h1>

<%= render 'form' %>